version: '3'

services:
  ldap:
    image: osixia/openldap:1.2.4
    hostname: ldap
    volumes:
      - ./data/ldap/data:/var/lib/ldap:Z
      - ./data/ldap/config:/etc/ldap/slapd.d:Z
    environment:
      LDAP_ADMIN_PASSWORD: "Admin123"
      LDAP_TLS: "false"
      LDAP_ORGANISATION: "Robert Koch-Institut"
      LDAP_DOMAIN: "intensivregister.de"
    ports:
      - 389:389
    restart: always
  mysql:
    image: mysql:5.7
    volumes:
    - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
  keycloak:
    build: ./docker
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JDBC_PARAMS: "characterEncoding=UTF-8&useSSL=false&requireSSL=false&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC&connectTimeout=30000"
    depends_on:
      - mysql
      - ldap
    ports:
      - 8080:8080